### ISSUE TITLE
Changing store region doesn't alter response

### ISSUE THREAD

**Issue by dano1066** [0xWaleed/playstation-store-api#1]
If I set the region to US I get a list of products and everything works great. If I change the region to UK, EU, RU or any other country code, I still get the same response. Am I using incorrect region codes or something?

**Comment by 0xwal** [comment]
I will fix it soon

**Comment by dano1066** [comment]
Changing the /SA/en/ section of the url seems to work. Changing to RU/ru seems to do the trick. Is there a list of all possible regions to use?
